---
- hosts: all

  vars:
    applications:
      # INFO ct 2014-04-22 most of the apps are commented out
      # because of the slow internet in cambodia
      # they should work just fine when un-commented
      # - adium
      # - alfred
      # - appcleaner
      # - atmonitor
      # - ccmenu
      # - charles
      # - cord
      # - dropbox
      # - firefox
      # - flux
      # - freemind
      # - gephi
      # - github
      # - google-chrome
      # - google-drive
      # - google-hangouts
      # - google-refine
      # - gpgtools
      # - handbrake
      # - imageoptim
      # - iterm2
      # - kaleidoscope
      # - kdiff3
      # - keepassx
      # - libreoffice
      # - mou
      # - nvalt
      # - onepassword
      # - owasp-zap
      # - pandoc
      # - sequel-pro
      # - sublime-text
      # - teamviewer
      # - the-unarchiver
      # - tunnelblick
      # - typinator
      # - vagrant
      # - virtualbox
    application_dir: /Applications
    brews:
      - ack
#      - chromedriver
      - docker
#      - hub
#      - ios-webkit-debug-proxy
      - rsync
      - zsh
#     - autojump
#     - cclive
#     - ffmpeg
#     - git-extras
#     - graphviz
#     # @see https://gist.github.com/jimbojsb/1630790
#     - highlight
#     - htop
#     - imagemagick
#     - jenkins-lts
#     - parallel
#      - phantomjs
#     - pwgen
#     - rbenv
      - rbenv-gem-rehash
      - rename
#     - ruby-install
#      - tesseract
#     - tig
#     - tmux
#     - tree
#     - vim
#     - wget
    apt_packages:
       - ack
       - autojump
       - build-essential
       - curl
       - git
       - git-core
       - git-extras
       - htop
       - python-apt
       - python-pip
       - rbenv
       - ruby
       - ruby-build
       - siege
       - terminator
       - tmux
       - tree
       - vim
       - zsh
    caskroom_dir: /usr/local/caskroom
    dotfiles_dir: "{{ ansible_env.HOME }}/dotfiles"
    email: info@christian-trabold.de
    username: "{{ ansible_env.USER }}"
    user_group: staff
    github_username: ctrabold
    home_dir: "{{ ansible_env.HOME }}"
    name: Christian Trabold
    zsh_path: /usr/local/bin/zsh

  tasks:
    - include: tasks/homebrew.yml tags=homebrew
      when: ansible_os_family == "Darwin"

    - include: tasks/packages_apt.yml tags=apt
      when: ansible_os_family == "Ubuntu"

    - include: tasks/zsh.yml tags=zsh
    - include: tasks/ruby.yml tags=ruby
    - include: tasks/vim.yml tags=vim
    - include: tasks/dotfiles.yml tags=dotfiles

  post_tasks:
    - debug: msg="Setup finished on {{ ansible_hostname }} running for {{ username }}. Have a good time!"
