---
- hosts: all
  roles:
   - common
#    - { role: common_mac_osx, tags: ['common', 'mac'], when: ansible_os_family == 'MacOSX' }
#    - { role: common_ubuntu, tags: ['common', 'ubuntu'], when: ansible_os_family == 'Ubuntu' }

  pre_tasks:
      - shell: echo "Starting setup on {{ ansible_hostname }}"

  post_tasks:
      - shell: echo "Setup finished on {{ ansible_hostname }} running for {{ login_user }}. Have a good time!"
