---
- hosts: all
  gather_facts: true
  - include: darwin.yml
    when:
  - include: ubuntu.yml
  post_tasks:
    - debug: msg="Setup finished on {{ ansible_hostname }} running for {{ username }}. Have a good time!"
