---
- name: Check Homebrew is installed
  stat: path=/usr/local/bin/brew
  register: brew_installed

- name: Install Homebrew
  shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  when: brew_installed.stat.exists == false

- name: Install homebrew taps
  shell: brew tap {{ item }}
  with_items:
    - caskroom/versions
    - homebrew/binary
    - homebrew/dupes
    - homebrew/versions

- name: Check rcm is installed
  stat: path=/usr/local/bin/rcup
  register: rcm_installed

- name: Install rcm for dotfiles management
  shell: brew tap thoughtbot/formulae && brew install rcm
  when: rcm_installed.stat.exists == false

- name: Check homebrew-cask is installed
  stat: path=/usr/local/bin/brew-cask.rb
  register: brew_cask_installed

- name: Install homebrew-cask
  shell: brew tap phinze/cask && brew install brew-cask
  when: brew_cask_installed.stat.exists == false

- name: Check for installed casks
  shell: brew cask list --appdir={{ application_dir }} --caskroom={{ caskroom_dir}} | grep {{ item }}
  register: installed_applications
  with_items: applications
  ignore_errors: true

- name: Install apps with brew-cask
  shell: brew cask install {{ item }} --appdir={{ application_dir }} --caskroom={{ caskroom_dir }}
  with_items: applications
  when: "item not in installed_applications.results|map(attribute='stdout')"

- name: Modify alfred scope to include caskroom
  shell: brew cask alfred link --appdir={{ application_dir }} --caskroom={{ caskroom_dir }}

- name: Install Homebrew libraries
  homebrew: name={{ item }} state=present
  with_items: brews
