---
- name: Packages | misc | Install utilities
  sudo: True
  apt: pkg={{ item }} state=installed
  with_items: apt_packages


  #
  # Keyboard layout
  #
- name: Settings | Check current layout
  shell: cat /etc/default/keyboard
  register: get_layout

- name: Settings | Set keyboard layout
  sudo: true
  template: src=templates/keyboard dest=/etc/default/keyboard

- name: Settings | Enable keyboard layout
  sudo: true
  command: dpkg-reconfigure -f noninteractive keyboard-configuration
  when: get_layout.stdout.find('ctrl:nocaps') == false


# TODO Setup apt-cacher first?
# http://askubuntu.com/questions/248996/howto-use-apt-cacher-ng-only-when-available#line-391
# https://help.ubuntu.com/community/Apt-Cacher-Server


# RCM dotfile management
#
# @see https://thoughtbot.github.io/rcm/
#
# TODO Check if can we install rcm via package manager to avoid this dance
- name: Packages | rcm | Check if rcm is installed
  stat: path=/usr/bin/rcup
  register: rcm_installed
  tags: rcm

- name: Packages | rcm | Download rcm package
  get_url: url=https://thoughtbot.github.io/rcm/debs/rcm_1.2.2-2_all.deb dest=/tmp/rcm_1.2.2-2_all.deb sha256sum=6cbc6d74f38786989c5780da84d261ff362afa161f70f63a386307e4838b3839
  when: rcm_installed.stat.exists == false
  tags: rcm

- name: Packages | rcm | Installs rcm package
  sudo: True
  apt: deb=/tmp/rcm_1.2.2-2_all.deb state=present
  when: rcm_installed.stat.exists == false
  tags: rcm


# API Document Browser like Dash on Ubuntu
#
# @see http://askubuntu.com/questions/154020/is-there-any-api-document-browser-like-dash-on-ubuntu
# @see http://zealdocs.org/usage.html

# NOTE: Zeal depends on Qt5, so for Ubuntu versions older than 14.04 (Trusty), Ubuntu SDK must be added as well:
# @see https://launchpad.net/~jerzy-kozera/+archive/zeal-ppa
- name: Packages | zeal | register SDK PPA for older ubuntus
  apt_repository: repo='ppa:ubuntu-sdk-team/ppa' state=present
  when: ansible_lsb.major_release|int < 14
  tags: zeal

- name: Packages | zeal | register zeal PPA
  apt_repository: repo='ppa:jerzy-kozera/zeal-ppa' state=present update_cache=true
  tags: zeal

- name: Packages | zeal | Install zeal
  apt: pkg=zeal state=present
  tags: zeal


# f.lux makes the color of your computer's display adapt to the time of day
# warm at night and like sunlight during the day.
#
# @see https://justgetflux.com/
- name: Packages | flux | register f.lux PPA
  apt_repository: repo='ppa:kilian/f.lux' state=present update_cache=true
  tags: flux

- name: Packages | flux | Install fluxgui
  apt: pkg=fluxgui state=present
  tags: flux


# 'nvalt' aka 'nvpy' on linux
#
# We use the tag 'nvalt' here in order to handle
# the installation of the tool with ONE tag for all OS
#
# @see https://github.com/cpbotha/nvpy/blob/master/docs/installation.rst#ubuntu--mint--debian-step-by-step-1

- name: Packages | nvalt | Install system packages
  sudo: True
  apt: pkg={{ item }} state=installed
  with_items:
    - python-markdown
    - python-tk
  tags: nvalt

- name: Packages | nvalt | Install nvalt
  pip: name=nvpy state=present
  tags: nvalt

  # TODO Use `dotfiles` repo for that?
- name: Packages | nvalt | Create configuration file
  template: src=templates/nvpy.cfg dest={{home_dir}}/.nvpy.cfg
  tags: nvalt

- name: Packages | nvalt | Create desktop integration file
  template: src=templates/vxlabs-nvpy.desktop dest={{ home_dir }}/vxlabs-nvpy.desktop
  tags: nvalt

- name: Packages | nvalt | Execute desktop integration
  command: xdg-desktop-menu install {{ home_dir }}/vxlabs-nvpy.desktop
  tags: nvalt
