---
  #
  # Mac OS X
  #

- name: Install rbenv
  homebrew: name={{ item }} state=present
  when: ansible_os_family == "Darwin"
  with_items:
    - rbenv
    - ruby-build


  #
  # Ubuntu
  #

  # INFO This is for gems that need to be compiled
  # like `nokogiri` and friends.
- name: Install ruby packages for compiling gems
  sudo: True
  apt: pkg={{item}} state=installed
  when: ansible_os_family == "Ubuntu"
  with_items:
    - autoconf
    - bison
    - build-essential
    - libopenssl-ruby
    - libreadline6
    - libreadline6-dev
    - libssl-dev
    - libxml2-dev
    - libxslt-dev
    - libyaml-dev
    - openssl
    - zlib1g
    - zlib1g-dev

- name: Install rbenv
  apt: package={{ item }} state=present
  when: ansible_os_family == "Ubuntu"
  with_items:
    - rbenv
    - ruby-build


  #
  # All OS
  #

- name: Install ruby versions
  command: rbenv install {{ item }} --skip-existing creates={{ home_dir }}/.rbenv/versions/{{ item }}
  with_items:
    - 1.9.3-p545
    - 2.0.0-p451
    # - 2.1.0

- name: Set global ruby versions
  command: rbenv global 2.0.0-p451

# Not working ATM
# @see http://stackoverflow.com/questions/22115936/install-bundler-gem-using-ansible
# @see http://mmoya.org/blog/2013/02/22/installing-rubyrbenv-with-ansible/
#
# - name: Install gems
#   command: RBENV_ROOT={{ rbenv_root }} bash -lc "gem install {{ item }}"
# #  when: bash -lc "gem list " | grep ^{{ item }}$ -v
#   with_items:
#     - bundler
#     - showoff
#     - middleman
