# My Thunderbid User Preferences

/**
 * These are my personal Firefox settings
 * which OVERRIDE the default settings in `pref.js`.
 *
 * They can NOT be overriden via `about:config`.
 *
 * @see http://kb.mozillazine.org/Modify_Thunderbird_settings
 * @see http://kb.mozillazine.org/Editing_configuration
 */

user_pref("calendar.alarms.playsound", false);
user_pref("calendar.categories.names", "Anniversary,Birthday,Business,Calls,Clients,Competition,Customer,Favorites,Follow up,Gifts,Holidays,Ideas,Issues,Meeting,Miscellaneous,Personal,Projects,Public Holiday,Status,Suppliers,Travel,Vacation");
user_pref("calendar.category.color.anniversary", "#333333");
user_pref("calendar.category.color.birthday", "#996633");
user_pref("calendar.category.color.business", "#FFFFCC");
user_pref("calendar.category.color.calls", "#99FF99");
user_pref("calendar.category.color.clients", "#FF9900");
user_pref("calendar.category.color.competition", "#CC9933");
user_pref("calendar.category.color.customer", "#CCCCCC");
user_pref("calendar.category.color.favorites", "#3366FF");
user_pref("calendar.category.color.follow_up", "#6600CC");
user_pref("calendar.category.color.gifts", "#FF99FF");
user_pref("calendar.category.color.holidays", "#663366");
user_pref("calendar.category.color.ideas", "#003333");
user_pref("calendar.category.color.issues", "#99FFFF");
user_pref("calendar.category.color.meeting", "#FFFF66");
user_pref("calendar.category.color.miscellaneous", "#FFCC00");
user_pref("calendar.category.color.personal", "#003333");
user_pref("calendar.category.color.projects", "#FFCC99");
user_pref("calendar.category.color.public_holiday", "#FFCC66");
user_pref("calendar.category.color.status", "#FFFF33");
user_pref("calendar.category.color.suppliers", "#000099");
user_pref("calendar.category.color.travel", "#663300");
user_pref("calendar.category.color.vacation", "#660000");
user_pref("calendar.google.calPrefs.christian@web-essentials.asia.googleUser", "christian@web-essentials.asia");
user_pref("calendar.list.sortOrder", "3fac1581-796a-445b-9e4b-2f153a67b9a4 bf81f344-308f-45b8-89ed-6fe237c10506");
user_pref("calendar.preferences.lightning.selectedTabIndex", 4);
user_pref("calendar.previousweeks.inview", 1);
user_pref("calendar.registry.3fac1581-796a-445b-9e4b-2f153a67b9a4.calendar-main-in-composite", true);
user_pref("calendar.registry.3fac1581-796a-445b-9e4b-2f153a67b9a4.name", "Home");
user_pref("calendar.registry.3fac1581-796a-445b-9e4b-2f153a67b9a4.type", "storage");
user_pref("calendar.registry.3fac1581-796a-445b-9e4b-2f153a67b9a4.uri", "moz-storage-calendar://");
user_pref("calendar.registry.bf81f344-308f-45b8-89ed-6fe237c10506.cache.enabled", true);
user_pref("calendar.registry.bf81f344-308f-45b8-89ed-6fe237c10506.calendar-main-default", true);
user_pref("calendar.registry.bf81f344-308f-45b8-89ed-6fe237c10506.calendar-main-in-composite", true);
user_pref("calendar.registry.bf81f344-308f-45b8-89ed-6fe237c10506.color", "");
user_pref("calendar.registry.bf81f344-308f-45b8-89ed-6fe237c10506.google.lastUpdated", "20140512T061826Z");
user_pref("calendar.registry.bf81f344-308f-45b8-89ed-6fe237c10506.imip.identity.key", "");
user_pref("calendar.registry.bf81f344-308f-45b8-89ed-6fe237c10506.name", "Google");
user_pref("calendar.registry.bf81f344-308f-45b8-89ed-6fe237c10506.type", "gdata");
user_pref("calendar.registry.bf81f344-308f-45b8-89ed-6fe237c10506.uri", "http://www.google.com/calendar/feeds/christian%40web-essentials.asia/public/basic");
user_pref("calendar.timezone.local", "Asia/Phnom_Penh");
user_pref("calendar.view.dayendhour", 20);
user_pref("calendar.view.useSystemColors", true);
user_pref("calendar.view.visiblehours", 8);
user_pref("calendar.week.start", 1);
user_pref("extensions.enigmail.keyManShowAllKeys", true);
user_pref("extensions.messagingmenu.enabled", false);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("ldap_2.autoComplete.directoryServer", "ldap_2.servers.directorywebessentialsas");
user_pref("ldap_2.autoComplete.useDirectory", true);
user_pref("ldap_2.servers.directorywebessentialsas.auth.dn", "ou=System &,Server,ou=people,dc=web-ess,entials,dc=asia");
user_pref("ldap_2.servers.directorywebessentialsas.auth.saslmech", "");
user_pref("ldap_2.servers.directorywebessentialsas.description", "directory.web-essentials.asia");
user_pref("ldap_2.servers.directorywebessentialsas.filename", "ldap.mab");
user_pref("ldap_2.servers.directorywebessentialsas.maxHits", 100);
user_pref("ldap_2.servers.directorywebessentialsas.uri", "ldaps://directory.web-essentials.asia/ou=people,dc=web-essentials,,dc=asia??sub?(objectclass=*)");
user_pref("ldap_2.servers.eds.description", "EDS Address Book Bootstrapper");
user_pref("ldap_2.servers.eds.dirType", 3);
user_pref("ldap_2.servers.eds.filename", "eds.mab");
user_pref("ldap_2.servers.eds.position", 1);
user_pref("ldap_2.servers.eds.uri", "moz-abedsdirectory://");
user_pref("mail.SpellCheckBeforeSend", true);
user_pref("mail.biff.play_sound", false);
user_pref("mail.biff.show_alert", false);
user_pref("mail.default_html_action", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.identity.id1.archive_folder", "imap://christian%40web-essentials.asia@imap.googlemail.com/[Gmail]/All Mail");
user_pref("mail.identity.id1.archives_folder_picker_mode", "1");
user_pref("mail.identity.id1.compose_html", false);
user_pref("mail.identity.id1.doBcc", false);
user_pref("mail.identity.id1.draft_folder", "imap://christian%40web-essentials.asia@imap.googlemail.com/[Gmail]/Drafts");
user_pref("mail.identity.id1.drafts_folder_picker_mode", "1");
user_pref("mail.identity.id1.encryptionpolicy", 0);
user_pref("mail.identity.id1.fcc_folder", "imap://christian%40web-essentials.asia@imap.googlemail.com/[Gmail]/Sent Mail");
user_pref("mail.identity.id1.fcc_folder_picker_mode", "1");
user_pref("mail.identity.id1.fullName", "Christian Trabold");
user_pref("mail.identity.id1.reply_on_top", 1);
user_pref("mail.identity.id1.sign_mail", false);
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.identity.id1.stationery_folder", "imap://christian%40web-essentials.asia@imap.googlemail.com/Templates");
user_pref("mail.identity.id1.tmpl_folder_picker_mode", "0");
user_pref("mail.identity.id1.useremail", "christian@web-essentials.asia");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.identity.id2.archive_folder", "imap://wp1140202-0@wp096.webpack.hosteurope.de/Archives");
user_pref("mail.identity.id2.attachPgpKey", false);
user_pref("mail.identity.id2.compose_html", false);
user_pref("mail.identity.id2.defaultEncryptionPolicy", 0);
user_pref("mail.identity.id2.doBcc", false);
user_pref("mail.identity.id2.draft_folder", "imap://wp1140202-0@wp096.webpack.hosteurope.de/Drafts");
user_pref("mail.identity.id2.drafts_folder_picker_mode", "0");
user_pref("mail.identity.id2.enablePgp", true);
user_pref("mail.identity.id2.encryptionpolicy", 0);
user_pref("mail.identity.id2.fcc_folder", "imap://wp1140202-0@wp096.webpack.hosteurope.de/Sent");
user_pref("mail.identity.id2.fcc_folder_picker_mode", "0");
user_pref("mail.identity.id2.fullName", "Christian Trabold");
user_pref("mail.identity.id2.openPgpHeaderMode", 0);
user_pref("mail.identity.id2.pgpKeyMode", 0);
user_pref("mail.identity.id2.pgpMimeMode", false);
user_pref("mail.identity.id2.pgpSignEncrypted", true);
user_pref("mail.identity.id2.pgpSignPlain", true);
user_pref("mail.identity.id2.reply_on_top", 1);
user_pref("mail.identity.id2.sig_bottom", true);
user_pref("mail.identity.id2.sign_mail", false);
user_pref("mail.identity.id2.smtpServer", "smtp2");
user_pref("mail.identity.id2.stationery_folder", "imap://wp1140202-0@wp096.webpack.hosteurope.de/Templates");
user_pref("mail.identity.id2.tmpl_folder_picker_mode", "0");
user_pref("mail.identity.id2.useremail", "info@christian-trabold.de");
user_pref("mail.identity.id2.valid", true);
user_pref("mail.inline_attachments", false);
user_pref("mail.last_msg_movecopy_target_uri", "imap://wp1140202-0@wp096.webpack.hosteurope.de/projects/WE");
user_pref("mail.openMessageBehavior", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.preferences.advanced.selectedTabIndex", 0);
user_pref("mail.preferences.applications.selectedTabIndex", 0);
user_pref("mail.preferences.compose.selectedTabIndex", 0);
user_pref("mail.preferences.display.selectedTabIndex", 0);
user_pref("mail.preferences.security.selectedTabIndex", 4);
user_pref("mail.server.server1.ageLimit", 1);
user_pref("mail.server.server1.applyToFlaggedMessages", false);
user_pref("mail.server.server1.cacheCapa.acl", false);
user_pref("mail.server.server1.cacheCapa.quota", true);
user_pref("mail.server.server1.check_new_mail", true);
user_pref("mail.server.server1.check_time", 30);
user_pref("mail.server.server1.cleanupBodies", false);
user_pref("mail.server.server1.cleanup_inbox_on_exit", true);
user_pref("mail.server.server1.daysToKeepBodies", 1);
user_pref("mail.server.server1.daysToKeepHdrs", 1);
user_pref("mail.server.server1.directory", "/home/christian/.thunderbird/22wxjytc.default/ImapMail/imap.googlemail.com");
user_pref("mail.server.server1.directory-rel", "[ProfD]ImapMail/imap.googlemail.com");
user_pref("mail.server.server1.downloadByDate", false);
user_pref("mail.server.server1.downloadUnreadOnly", false);
user_pref("mail.server.server1.hostname", "imap.googlemail.com");
user_pref("mail.server.server1.is_gmail", true);
user_pref("mail.server.server1.keepUnreadOnly", false);
user_pref("mail.server.server1.login_at_startup", true);
user_pref("mail.server.server1.max_cached_connections", 5);
user_pref("mail.server.server1.moveOnSpam", true);
user_pref("mail.server.server1.name", "christian@web-essentials.asia");
user_pref("mail.server.server1.namespace.personal", "\"\"");
user_pref("mail.server.server1.numHdrsToKeep", 2000);
user_pref("mail.server.server1.port", 993);
user_pref("mail.server.server1.purgeSpam", true);
user_pref("mail.server.server1.purgeSpamInterval", 2);
user_pref("mail.server.server1.serverIDResponse", "(\"name\" \"GImap\" \"vendor\" \"Google, Inc.\" \"support-url\" \"http://support.google.com/mail\" \"version\" \"gmail_imap_140504.00_p1\" \"remote-host\" \"119.82.252.95\")");
user_pref("mail.server.server1.socketType", 3);
user_pref("mail.server.server1.spamActionTargetAccount", "imap://christian%40web-essentials.asia@imap.googlemail.com");
user_pref("mail.server.server1.spamActionTargetFolder", "imap://christian%40web-essentials.asia@imap.googlemail.com/Junk");
user_pref("mail.server.server1.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server1.timeout", 29);
user_pref("mail.server.server1.type", "imap");
user_pref("mail.server.server1.useServerFilter", true);
user_pref("mail.server.server1.userName", "christian@web-essentials.asia");
user_pref("mail.server.server2.ageLimit", 1);
user_pref("mail.server.server2.applyToFlaggedMessages", false);
user_pref("mail.server.server2.cleanupBodies", false);
user_pref("mail.server.server2.daysToKeepBodies", 1);
user_pref("mail.server.server2.daysToKeepHdrs", 1);
user_pref("mail.server.server2.directory-rel", "[ProfD]Mail/Local Folders");
user_pref("mail.server.server2.downloadByDate", false);
user_pref("mail.server.server2.downloadUnreadOnly", false);
user_pref("mail.server.server2.hostname", "Local Folders");
user_pref("mail.server.server2.keepUnreadOnly", false);
user_pref("mail.server.server2.name", "Local Folders");
user_pref("mail.server.server2.numHdrsToKeep", 2000);
user_pref("mail.server.server2.spamActionTargetAccount", "mailbox://nobody@Local%20Folders");
user_pref("mail.server.server2.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server2.type", "none");
user_pref("mail.server.server2.userName", "nobody");
user_pref("mail.server.server4.ageLimit", 1);
user_pref("mail.server.server4.applyToFlaggedMessages", false);
user_pref("mail.server.server4.cacheCapa.acl", false);
user_pref("mail.server.server4.cacheCapa.quota", true);
user_pref("mail.server.server4.check_new_mail", true);
user_pref("mail.server.server4.check_time", 30);
user_pref("mail.server.server4.cleanupBodies", false);
user_pref("mail.server.server4.cleanup_inbox_on_exit", true);
user_pref("mail.server.server4.daysToKeepBodies", 1);
user_pref("mail.server.server4.daysToKeepHdrs", 1);
user_pref("mail.server.server4.directory-rel", "[ProfD]ImapMail/wp096.webpack.hosteurope.de");
user_pref("mail.server.server4.downloadByDate", false);
user_pref("mail.server.server4.downloadUnreadOnly", false);
user_pref("mail.server.server4.hostname", "wp096.webpack.hosteurope.de");
user_pref("mail.server.server4.keepUnreadOnly", false);
user_pref("mail.server.server4.login_at_startup", true);
user_pref("mail.server.server4.max_cached_connections", 5);
user_pref("mail.server.server4.moveOnSpam", true);
user_pref("mail.server.server4.moveTargetMode", 1);
user_pref("mail.server.server4.name", "info@christian-trabold.de");
user_pref("mail.server.server4.namespace.personal", "\"\"");
user_pref("mail.server.server4.numHdrsToKeep", 2000);
user_pref("mail.server.server4.port", 993);
user_pref("mail.server.server4.purgeSpam", true);
user_pref("mail.server.server4.purgeSpamInterval", 2);
user_pref("mail.server.server4.socketType", 3);
user_pref("mail.server.server4.spamActionTargetAccount", "imap://wp1140202-0@wp096.webpack.hosteurope.de");
user_pref("mail.server.server4.spamActionTargetFolder", "imap://wp1140202-0@wp096.webpack.hosteurope.de/SPAM");
user_pref("mail.server.server4.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server4.timeout", 29);
user_pref("mail.server.server4.type", "imap");
user_pref("mail.server.server4.useServerFilter", true);
user_pref("mail.server.server4.userName", "wp1140202-0");
user_pref("mail.smtpserver.smtp1.authMethod", 3);
user_pref("mail.smtpserver.smtp1.description", "Google Mail");
user_pref("mail.smtpserver.smtp1.hostname", "smtp.googlemail.com");
user_pref("mail.smtpserver.smtp1.port", 465);
user_pref("mail.smtpserver.smtp1.try_ssl", 3);
user_pref("mail.smtpserver.smtp1.username", "christian@web-essentials.asia");
user_pref("mail.smtpserver.smtp2.authMethod", 3);
user_pref("mail.smtpserver.smtp2.hostname", "wp096.webpack.hosteurope.de");
user_pref("mail.smtpserver.smtp2.port", 465);
user_pref("mail.smtpserver.smtp2.try_ssl", 3);
user_pref("mail.smtpserver.smtp2.username", "wp1140202-0");
user_pref("mail.smtpservers", "smtp1,smtp2");
user_pref("mail.spam.manualMark", true);
user_pref("mail.spam.manualMarkMode", 1);
user_pref("mail.spam.markAsReadOnSpam", true);
user_pref("mail.spam.version", 1);
user_pref("mail.startup.enabledMailCheckOnce", true);
user_pref("mail.ui-rdf.version", 5);
user_pref("mailnews.database.global.datastore.id", "75aa16de-1469-4f12-8c0f-243e63e3541");
user_pref("mailnews.display.html_sanitizer.allowed_tags.migrated", true);
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.reply_in_default_charset", true);
user_pref("mailnews.send_default_charset", "UTF-8");
user_pref("mailnews.start_page.enabled", false);
user_pref("mailnews.start_page_override.mstone", "24.2.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("mailnews.ui.junk.firstuse", false);
user_pref("mailnews.view_default_charset", "UTF-8");
user_pref("network.cookie.cookieBehavior", 2);
user_pref("network.cookie.prefsMigrated", true);
