---
- name: Install homebrew taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - caskroom/versions
    - homebrew/binary
    - homebrew/dupes
    - homebrew/versions
    - thoughtbot/formulae

- name: Install apps with brew-cask
  homebrew_cask: name={{ item }} state=installed
  with_items: homebrew_casks
  ignore_errors: yes

- name: Install quicklook plugins with brew-cask (https://github.com/sindresorhus/quick-look-plugins)
  homebrew_cask: name={{ item }} state=installed
  with_items:
    - qlcolorcode
    - qlstephen
    - qlmarkdown
    - quicklook-json
    - qlprettypatch
    - quicklook-csv
    - betterzipql
    - qlimagesize
    - webpquicklook
    - suspicious-package

- name: Install 'homebrew' packages
  homebrew: name={{ item }} state=present
  with_items: homebrew_packages

- name: Cleanup 'homebrew'
  command: brew prune && brew cleanup && brew tap --repair

- name: Write launch agent config for updating homebrew automatically
  copy: src=homebrew.update.plist
        dest={{ home_dir }}/Library/LaunchAgents
        mode=0755

- name: Load launchagent config
  command: launchctl load {{ home_dir }}/Library/LaunchAgents/homebrew.update.plist

- name: Start homebrew update lauch agent
  command: launchctl start homebrew.update

- name: Cleanup dock
  command: dockutil --remove all

# FONTS
# @see https://github.com/caskroom/homebrew-fonts
- name: Check caskroom-fonts is installed
  homebrew_tap: tap=caskroom/fonts state=present

- name: Install fonts
  homebrew_cask: name={{ item }} state=present
  with_items:
    - font-inconsolata-dz-for-powerline
    - font-inconsolata
    - font-meslo-lg-for-powerline
    - font-ubuntu
