---
- name: Check Homebrew is installed
  stat: path=/usr/local/bin/brew
  register: brew_installed

- name: Install Homebrew
  shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  when: brew_installed.stat.exists == false

- name: Remove outdated homebrew taps
  homebrew_tap: tap={{ item }} state=absent
  with_items:
    - phinze/cask

- name: Install homebrew taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - caskroom/cask
    - caskroom/versions
    - homebrew/binary
    - homebrew/dupes
    - homebrew/versions
    - thoughtbot/formulae

- name: Install apps with brew-cask
  homebrew_cask: name={{ item }} state=installed
  with_items: applications
  ignore_errors: yes

- name: Install 'homebrew' libraries
  homebrew: name={{ item }} state=present
  with_items: brews

- name: Cleanup 'homebrew'
  command: brew prune && brew cleanup && brew tap --repair

- name: Cleanup dock
  command: dockutil --remove all
