---
- name: Install utilities
  sudo: True
  apt: pkg={{item}} state=installed
  with_items:
     - ack
     - autojump
     - build-essential
     - curl
     - git
     - git-core
     - git-extras
     - rbenv
     - ruby
     - ruby-build
     - siege
     - terminator
     - tmux
     - tree
     - vim
     - zsh
