---
# @see https://github.com/caskroom/homebrew-fonts
- name: Check caskroom-fonts is installed
  homebrew_tap: tap=caskroom/fonts state=present

- name: Install fonts
  homebrew_cask: name={{ item }} state=present
  with_items:
    - font-inconsolata-dz-for-powerline
    - font-inconsolata
    - font-meslo-lg-for-powerline
    - font-ubuntu
